# Generated by Django 2.1 on 2018-09-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='get_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
