# Generated by Django 2.1 on 2018-09-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_bookmarked'),
        ('profiles', '0002_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to='articles.Article'),
        ),
    ]
