# Generated by Django 2.1 on 2018-09-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_bookmarks'),
        ('profiles', '0003_profile_follows'),
    ]

    operations = [
    ]
