# Generated by Django 2.1 on 2018-09-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180913_0816'),
        ('articles', '0003_auto_20180913_1553'),
    ]

    operations = [
    ]
