# Generated by Django 2.1 on 2018-09-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articleratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ratings_counter',
            field=models.IntegerField(default=0),
        ),
    ]
