# Generated by Django 2.1 on 2018-09-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_ratings_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleratings',
            name='counter',
        ),
    ]
