# Generated by Django 2.1 on 2018-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_merge_20180913_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
